<template>
  <div>
    <div class="title">
      <h2>流行音樂篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>

    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">其他聯絡方式</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>李宗盛</p>
          </td>
          <td>
            <p>李吉他</p>
          </td>
          <td>
            <p>http://tw.leeguitars.com/</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>謝金燕</p>
          </td>
          <td>
            <p>一直打不倒</p>
          </td>
          <td>
            <p>https://www.facebook.com/JeannieHsiehbbb/</p>
          </td>
          <td>
            <p>1990年出道</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>盧靜子</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://business.facebook.com/Im.Ceko/</p>
          </td>
          <td>
            <p>原住民一代歌后</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北爵士大樂隊</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>http://www.tjo.com.tw/</p>
            <p>https://www.facebook.com/taipeijazzorchestra</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蔡健雅</p>
          </td>
          <td>
            <p>水晶共振經紀公司</p>
          </td>
          <td>
            <p>https://www.facebook.com/tanyachuaofficial</p>
            <p>crystalresonance2010@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>張信哲</p>
          </td>
          <td>
            <p>潮水音樂有限公司</p>
          </td>
          <td>
            <p>https://www.facebook.com/OfficialJeffChang</p>
            <p>tenplus.founder@gmail.com</p>
          </td>
          <td>
            <p>1990年代華語樂壇代表人物，被稱為華語樂壇的「情歌王子」。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>郭婷筠</p>
          </td>
          <td>
            <p>時代創藝</p>
          </td>
          <td>
            <p>https://www.facebook.com/tessi0905/</p>
            <p>starjobwinnie@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>愛客樂iColor</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://reurl.cc/VjlWkN</p>
            <p>goodtone.elsa@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>Monique Chao默默</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/moniquechaojazz</p>
            <p>vingtmoni@gmail.com</p>
          </td>
          <td>
            <p>爵士音樂作曲家</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>The Tic Tac</p>
          </td>
          <td>
            <p>Strikingly</p>
          </td>
          <td>
            <p>thetictacband@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>玖壹壹</p>
          </td>
          <td>
            <p>滾石唱片</p>
          </td>
          <td>
            <p>https://www.facebook.com/JiuYiYi/</p>
            <p>jiuyiyi911@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>動力火車</p>
          </td>
          <td>
            <p>華研國際音樂</p>
          </td>
          <td>
            <p>https://www.him.com.tw/artistscon1.php?mid=84</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>彭佳慧</p>
          </td>
          <td>
            <p>索尼音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/juliastar888</p>
            <p>su6834@gmail.com（蘇小姐）</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>辛曉琪</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/winniehsinfanspage</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蕭煌奇</p>
          </td>
          <td>
            <p>好莉嗨文創有限公司</p>
          </td>
          <td>
            <p>https://www.facebook.com/RickyHsiao</p>
            <p>chenlily.3@gmail.com（陳小姐）</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>MAFANA</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/Mafanaband</p>
            <p>sufinmafana@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>Original Brewing原味醞釀</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/original.brewing.taitung/</p>
            <p>sakinu1103@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>周華健</p>
          </td>
          <td>
            <p>滾石唱片</p>
          </td>
          <td>
            <p>http://wakin.com/</p>
            <p>https://www.facebook.com/wakinchauofficial</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蔡詩芸</p>
          </td>
          <td>
            <p>混血兒娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/ddomchoy</p>
            <p>empirediguo@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>林俊傑</p>
          </td>
          <td>
            <p>華納音樂</p>
          </td>
          <td>
            <p>https://www.jjlin.com/</p>
            <p>https://www.facebook.com/JJLin</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>飛兒樂團</p>
          </td>
          <td>
            <p>華研國際音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/firband</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>陳建年</p>
          </td>
          <td>
            <p>角頭音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/paudull.taiwan</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>黃宇寒</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://reurl.cc/ZrvNpp</p>
            <p>waymusicstudio@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>曾瑋中</p>
          </td>
          <td>
            <p>時代創藝</p>
          </td>
          <td>
            <p>https://www.facebook.com/kuljelje.ix.xx</p>
            <p>starjobwinnie@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>黃瑞豐</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.richhuang.org</p>
            <p>https://www.facebook.com/Richdrumonly</p>
          </td>
          <td>
            <p>有「臺灣鼓王」之美名，2020年榮獲第三十一屆金曲獎特別貢獻獎。</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>高爾宣</p>
          </td>
          <td>
            <p>龍大謝音樂</p>
          </td>
          <td>
            <p>http://www.skrpresents.com/osn-396402924623459.html</p>
            <p>https://www.facebook.com/osnrapper</p>
            <p>osnkaoofficial@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>桑布伊</p>
          </td>
          <td>
            <p>風潮音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/Sangpuy</p>
            <p>info@sangpuy.com（周先生）</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>謝銘祐</p>
          </td>
          <td>
            <p>三川娛樂有限公司</p>
          </td>
          <td>
            <p>https://www.facebook.com/hsiehmingyo</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>羅思容</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/SirongGomoteu</p>
            <p>http://www.treesmusic.com/artist/Sirong/sirong.htm</p>
            <p>rose.k2200@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>黃小琥</p>
          </td>
          <td>
            <p>星光娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/superTigerHuang</p>
            <p>zack0301@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>許富凱</p>
          </td>
          <td>
            <p>凱聲影藝</p>
          </td>
          <td>
            <p>https://www.facebook.com/Henryhsu0917/</p>
            <p>joe19770302@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>盧廣仲</p>
          </td>
          <td>
            <p>添翼創越工作室</p>
          </td>
          <td>
            <p>https://www.facebook.com/Captain.Lu</p>
            <p>team.ear@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>木曜四超玩</p>
          </td>
          <td>
            <p>麥卡貝網路電視</p>
          </td>
          <td>
            <p>https://www.facebook.com/Muyao4</p>
          </td>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
