<template>
  <div>
    <div class="title">
      <h2>西樂及混合編制篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>
    <h3>一、樂團</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>基隆交響管樂團</p>
          </td>
          <td>
            <p>李偉立</p>
          </td>
          <td>
            <p>基隆市信義區深澳坑路125巷57號</p>
            <p>0939-373-691</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/KLSWO/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>幼獅交響管樂團</p>
          </td>
          <td>
            <p>鄭文龍</p>
          </td>
          <td>
            <p>基隆市中山區文化路199之1號</p>
            <p>02-2423-3717</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/CYCWINDORCHESTRA/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>基隆城市愛樂室內暨管弦樂團</p>
          </td>
          <td>
            <p>林文壽</p>
          </td>
          <td>
            <p>基隆市中山區中山一路31號1樓</p>
            <p>02-2423-1415</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/keelungcpo/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>國家交響樂團</p>
          </td>
          <td>
            <p>郭玟岑</p>
          </td>
          <td>
            <p>臺北市中正區中山南路21-1號</p>
            <p>02-3393-9888</p>
          </td>
          <td>
            <a target="_" href="http://npac-nso.org/zh/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣鈴木樂團</p>
          </td>
          <td>
            <p>李子韻</p>
          </td>
          <td>
            <p>臺北市中正區羅斯福路四段68號11樓之23</p>
            <p>02-2366-0888</p>
          </td>
          <td>
            <a href="mailto:passioncello@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>汲音木管室內樂團</p>
          </td>
          <td>
            <p>楊蕙祺</p>
          </td>
          <td>
            <p>臺北市中正區詔安街35之1號7樓<br>02-2369-4802</p>
          </td>
          <td>
            <a href="mailto:amatwn@ms17.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣耶魯室內樂團</p>
          </td>
          <td>
            <p>王勳聖</p>
          </td>
          <td>
            <p>臺北市中正區襄陽路23號</p>
            <p>02-2312-4248</p>
          </td>
          <td>
            <a href="mailto:tw.yale.ensemble@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北愛樂管弦樂團</p>
          </td>
          <td>
            <p>賴文福</p>
          </td>
          <td>
            <p>臺北市中正區濟南路一段7號</p>
            <p>02-2397-0979</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taipeiphil.org/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>吹笛人室內樂團</p>
          </td>
          <td>
            <p>張翠琳</p>
          </td>
          <td>
            <p>臺北市中正區新生南路一段16號3樓之1</p>
            <p>02-2321-9035</p>
          </td>
          <td>
            <a target="_" href="https://www.jdfe-1998.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北銅管五重奏團</p>
          </td>
          <td>
            <p>賴日昇</p>
          </td>
          <td>
            <p>臺北市中正區汀州路二段127巷18號4樓</p>
            <p>02-2365-5681</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台灣絃樂團</p>
          </td>
          <td>
            <p>鄭斯鈞</p>
          </td>
          <td>
            <p>臺北市中正區臨沂街76巷4之1號地下1樓</p>
            <p>02-2321-8168</p>
          </td>
          <td>
            <a target="_" href="http://www.atstrings.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>和平交響樂團</p>
          </td>
          <td>
            <p>劉容舟</p>
          </td>
          <td>
            <p>臺北市中正區汀州路三段33號4樓</p>
            <p>0937-878-251</p>
          </td>
          <td>
            <a href="mailto:snoopyshark@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>藝心弦樂四重奏</p>
          </td>
          <td>
            <p>張琪翊</p>
          </td>
          <td>
            <p>臺北市中正區忠孝東路一段76號4樓之1</p>
            <p>0912-333-064</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/artrichquartet/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北打擊樂團</p>
          </td>
          <td>
            <p>尤文傑</p>
          </td>
          <td>
            <p>臺北市信義區永吉路201號地下1樓</p>
            <p>02-2765-6145</p>
          </td>
          <td>
            <a target="_" href="https://tpperc.weebly.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>詠樂集</p>
          </td>
          <td>
            <p>葉青青</p>
          </td>
          <td>
            <p>臺北市信義區吳興街284巷24弄72號2樓</p>
            <p>02-7720-0288</p>
          </td>
          <td>
            <a href="mailto:singing99yeh@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>雙溪樂集</p>
          </td>
          <td>
            <p>嚴福榮</p>
          </td>
          <td>
            <p>臺北市內湖區瑞陽里陽光街68巷162號5樓</p>
            <p>0978-372-100</p>
          </td>
          <td>
            <a href="mailto:scusca2011@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>活泉室內樂團</p>
          </td>
          <td>
            <p>謝奇儔</p>
          </td>
          <td>
            <p>臺北市內湖區成功路五段46號6樓</p>
            <p>0920-503-021</p>
          </td>
          <td>
            <a href="mailto:livesprings@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>春秋樂集</p>
          </td>
          <td>
            <p>邱君強</p>
          </td>
          <td>
            <p>臺北市北投區大業路166號11樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>朱宗慶打擊樂團</p>
          </td>
          <td>
            <p>朱宗慶</p>
          </td>
          <td>
            <p>臺北市北投區大業路10號6樓</p>
            <p>02-2891-9900</p>
          </td>
          <td>
            <a target="_" href="http://www.jpg.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣打擊樂團</p>
          </td>
          <td>
            <p>何鴻棋</p>
          </td>
          <td>
            <p>臺北市北投區大業路10號地下1樓</p>
            <p>02-2891-9900</p>
          </td>
          <td>
            <a target="_" href="http://www.jpg.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>亞青樂集</p>
          </td>
          <td>
            <p>陳玠如</p>
          </td>
          <td>
            <p>臺北市北投區中和街20巷2號4樓之18</p>
          </td>
          <td>
            <a href="mailto:jieru.chen1015@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>躍動打擊樂團</p>
          </td>
          <td>
            <p>劉叔康</p>
          </td>
          <td>
            <p>臺北市北投區大業路10號地下1樓</p>
            <p>02-2891-9900</p>
          </td>
          <td>
            <a target="_" href="http://www.jpg.org.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北豎琴室內樂集</p>
          </td>
          <td>
            <p>邱孟璐</p>
          </td>
          <td>
            <p>臺北市中山區民權西路73號1樓</p>
            <p>02-2597-7789</p>
          </td>
          <td>
            <a target="_" href="http://www.harp.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>玩弦四度</p>
          </td>
          <td>
            <p>黃偉駿</p>
          </td>
          <td>
            <p>臺北市大安區師大路105巷18號9樓之2</p>
            <p>0911-817-939</p>
          </td>
          <td>
            <a href="mailto:interestringquartet@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>佳音室內樂團</p>
          </td>
          <td>
            <p>陳平三</p>
          </td>
          <td>
            <p>臺北市大安區信義路四段306號15樓</p>
            <p>02-2701-6769 #620</p>
          </td>
          <td>
            <a target="_" href="https://m.facebook.com/chiayinchamberorchestra">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>黑種籽單簧管合奏團</p>
          </td>
          <td>
            <p>宋威德</p>
          </td>
          <td>
            <p>臺北市大安區建國南路一段304巷26號地下1樓之1</p>
            <p>02-2666-6377</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HeySeed.Clarinet/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>新北市交響樂團</p>
          </td>
          <td>
            <p>廖年賦</p>
          </td>
          <td>
            <p>臺北市大安區和平東路三段49號14樓</p>
            <p>02-2702-7253</p>
          </td>
          <td>
            <a href="mailto:tmso1990@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>透鳴單簧管重奏團</p>
          </td>
          <td>
            <p>高承胤</p>
          </td>
          <td>
            <p>臺北市大安區龍淵里和平東路二段96巷17弄6號</p>
            <p>02-2944-2244</p>
          </td>
          <td>
            <a href="mailto:tscle.tw@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北愛樂少年樂團</p>
          </td>
          <td>
            <p>劉葳莉</p>
          </td>
          <td>
            <p>臺北市大安區敦化南路一段233巷28號B1</p>
            <p>02-2773-3691</p>
          </td>
          <td>
            <a href="mailto:tpf60@tpf.org.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣璇音雅集</p>
          </td>
          <td>
            <p>陳茂萱</p>
          </td>
          <td>
            <p>臺北市大安區羅斯福路二段93號17樓之7</p>
            <p>02-2362-6128</p>
          </td>
          <td>
            <a href="mailto:sufl2004@mail.nhctc.edu.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>T-Brass頂尖銅管</p>
          </td>
          <td>
            <p>陳中昇</p>
          </td>
          <td>
            <p>臺北市大安區杭州南路二段71號5樓</p>
            <p>0919-897-709</p>
          </td>
          <td>
            <a href="mailto:Tbrass2017@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>那娜擊樂二重奏NanaFormosa Percussion Duo</p>
          </td>
          <td>
            <p>張育瑛</p>
          </td>
          <td>
            <p>臺北市大安區延吉街137巷24號5樓</p>
            <p>02-2773-7611</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/NanaFormosa.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Clap&amp;Tap室內管弦樂團</p>
          </td>
          <td>
            <p>蕭育霆</p>
          </td>
          <td>
            <p>臺北市大安區敦化南路二段164號3樓</p>
            <p>0911-135-413</p>
          </td>
          <td>
            <a href="mailto:claptap.taipei@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>1002打擊樂團</p>
          </td>
          <td>
            <p>陳哲輝</p>
          </td>
          <td>
            <p>臺北市大安區和平東路一段183巷3弄3號1樓</p>
            <p>02-2394-1048</p>
          </td>
          <td>
            <a href="mailto:e1002@seed.net.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>葉樹涵銅管五重奏樂團</p>
          </td>
          <td>
            <p>葉樹涵</p>
          </td>
          <td>
            <p>臺北市大安區羅斯福路三段125號8樓</p>
            <p>02-3365-2114</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>亞太弦樂四重奏團</p>
          </td>
          <td>
            <p>黃維明</p>
          </td>
          <td>
            <p>臺北市大安區杭州南路二段29之5號</p>
            <p>02-3322-1428</p>
          </td>
          <td>
            <a target="_" href="http://www.chambermusic.org.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>MIT米特薩克斯風重奏團</p>
          </td>
          <td>
            <p>陳冠文</p>
          </td>
          <td>
            <p>臺北市大安區仁愛路三段5巷5弄15號1樓</p>
            <p>02-2367-0039</p>
          </td>
          <td>
            <a target="_" href="https://www.mit-sax.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北弦樂團</p>
          </td>
          <td>
            <p>彭廣林</p>
          </td>
          <td>
            <p>臺北市大安區復興南路一段360號3樓之3</p>
          </td>
          <td>
            <a href="mailto:gwanglinpeng@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>人間樂集</p>
          </td>
          <td>
            <p>翁立美</p>
          </td>
          <td>
            <p>臺北市大安區安和路一段33號4樓</p>
            <p>02-2776-2020</p>
          </td>
          <td>
            <a href="mailto:winnietheflute@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北世紀交響樂團</p>
          </td>
          <td>
            <p>廖陳盧寧</p>
          </td>
          <td>
            <p>臺北市大安區和平東路三段49號14樓</p>
            <p>02-2702-7253</p>
          </td>
          <td>
            <a target="_" href="http://www.century.org.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>陽光台北交響樂團</p>
          </td>
          <td>
            <p>孫愛光</p>
          </td>
          <td>
            <p>臺北市大安區泰順街54巷16號1樓</p>
          </td>
          <td>
            <a target="_" href="http://www.suntaipeiphil.org/index.html">連結</a><br>
            <a href="mailto:sun.taipei.phil@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>樂興之時管絃樂團</p>
          </td>
          <td>
            <p>江靖波</p>
          </td>
          <td>
            <p>臺北市大安區仁愛路四段112巷18號地下1樓</p>
            <p>02-2505-0859</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/momentmusical/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>弦外之音團</p>
          </td>
          <td>
            <p>謝婉玲</p>
          </td>
          <td>
            <p>臺北市大安區敦化南路一段160巷16號4樓</p>
            <p>02-2781-2306</p>
          </td>
          <td>
            <a href="mailto:proartcello@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>含光藝術工作室</p>
          </td>
          <td>
            <p>廖銘星</p>
          </td>
          <td>
            <p>臺北市大安區和平東路一段183巷8之1號2樓</p>
            <p>02-2391-0918</p>
          </td>
          <td>
            <a href="mailto:hanart.taiwan@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北市立交響樂團</p>
          </td>
          <td>
            <p>何康國</p>
          </td>
          <td>
            <p>臺北市八德路三段25號7樓</p>
            <p>02-2578-6731</p>
          </td>
          <td>
            <a target="_" href="https://www.tso.gov.taipei/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>徐家駒低音管室內樂團</p>
          </td>
          <td>
            <p>徐家駒</p>
          </td>
          <td>
            <p>臺北市松山區八德路四段91巷3弄33號4樓</p>
            <p>02-2286-9792</p>
          </td>
          <td>
            <a href="mailto:fagott@ms21.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>歐陽伶宜大提琴音樂方程式</p>
          </td>
          <td>
            <p>歐陽伶宜</p>
          </td>
          <td>
            <p>臺北市松山區民生東路五段69巷1弄20號1樓</p>
            <p>0910-862-301</p>
          </td>
          <td>
            <a href="mailto:cello01.ouyang@hotmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>安徒生和莫札特的創意</p>
          </td>
          <td>
            <p>林奕君</p>
          </td>
          <td>
            <p>臺北市松山區光復北路100巷11號</p>
            <p>02-2577-2816</p>
          </td>
          <td>
            <a target="_" href="http://www.amgroup.com.tw/show_page/page/20">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>曉韵古樂團</p>
          </td>
          <td>
            <p>蔡佳璇</p>
          </td>
          <td>
            <p>臺北市松山區南京東路五段59巷27之5號</p>
            <p>0988-292-234</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/barockensembletaipei">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>經典大提琴室內樂團</p>
          </td>
          <td>
            <p>蔡福桂</p>
          </td>
          <td>
            <p>0931-713-870</p>
          </td>
          <td>
            <a href="mailto:fred2002m@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣愛樂室內樂團</p>
          </td>
          <td>
            <p>林伸龍</p>
          </td>
          <td>
            <p>臺北市中山區明水路453號1樓</p>
            <p>02-8509-1050</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>灣聲樂團</p>
          </td>
          <td>
            <p>李哲藝</p>
          </td>
          <td>
            <p>臺北市中山區撫順街2號9樓</p>
            <p>02-2593-6586</p>
          </td>
          <td>
            <a target="_" href="http://www.onesongorchestra.com/">連結</a><br>
            <a href="mailto:onesongorchestra@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺灣管樂團</p>
          </td>
          <td>
            <p>林昀宏</p>
          </td>
          <td>
            <p>臺北市中山區中山北路二段93巷17號8樓之2</p>
            <p>02-2624-1035</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TaiwanWindEnsemble">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>魔笛單簧管四重奏</p>
          </td>
          <td>
            <p>林佩筠</p>
          </td>
          <td>
            <p>臺北市中山區吉林路12之5號2樓</p>
            <p>02-3765-1985</p>
          </td>
          <td>
            <a href="mailto:pylin@cm1.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北音樂家室內樂團</p>
          </td>
          <td>
            <p>劉怡君</p>
          </td>
          <td>
            <p>臺北市中山區長春路190號8樓</p>
            <p>02-2369-4802</p>
          </td>
          <td>
            <a href="mailto:amatwn@ms17.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>福爾摩沙四重奏</p>
          </td>
          <td>
            <p>葉垂青</p>
          </td>
          <td>
            <p>臺北市中山區建國北路二段33號2樓</p>
            <p>02-2509-1226</p>
          </td>
          <td>
            <a target="_" href="http://fcmf.com.tw/member/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>十方樂集</p>
          </td>
          <td>
            <p>徐伯年</p>
          </td>
          <td>
            <p>臺北市大同區民族西路187巷4號</p>
            <p>02-2593-5811</p>
          </td>
          <td>
            <a target="_" href="http://www.musforum.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>福爾摩沙廣播交響樂團</p>
          </td>
          <td>
            <p>劉昱昀</p>
          </td>
          <td>
            <p>新北市新莊區中港一街90之3號</p>
            <p>0929-356-282</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/福爾摩沙廣播交響樂團-179921122093836">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>新北市管絃樂團</p>
          </td>
          <td>
            <p>張潔茹</p>
          </td>
          <td>
            <p>新北市新莊區泰順街24號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/NTCCOmusic/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣傑出音樂家室內樂團</p>
          </td>
          <td>
            <p>鄭琨琳</p>
          </td>
          <td>
            <p>新北市新莊區幸福路69號2樓</p>
            <p>0929-356-282</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>欣響室內管樂團</p>
          </td>
          <td>
            <p>陳順發</p>
          </td>
          <td>
            <p>新北市新莊區中正路173號2樓</p>
            <p>02-2993-3893</p>
          </td>
          <td>
            <a href="mailto:shinsharn@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>口口實驗室</p>
          </td>
          <td>
            <p>蔡銘</p>
          </td>
          <td>
            <p>新北市新莊區龍安路487巷2弄6號3樓</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/kokolab.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>歐普思室內樂集</p>
          </td>
          <td>
            <p>洪余昇</p>
          </td>
          <td>
            <p>新北市新莊區新泰路179號2樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新北愛樂管弦樂團</p>
          </td>
          <td>
            <p>崔悟凡</p>
          </td>
          <td>
            <p>新北市新莊區中和街204巷6號5樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新北市交響樂團</p>
          </td>
          <td>
            <p>廖嘉齡</p>
          </td>
          <td>
            <p>新北市永和區竹林路91巷43弄6號3樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新北市室內管絃樂團</p>
          </td>
          <td>
            <p>伍穎慧</p>
          </td>
          <td>
            <p>新北市永和區竹林路42巷13號3樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>陳維哲低音提琴室內樂團</p>
          </td>
          <td>
            <p>陳維哲</p>
          </td>
          <td>
            <p>新北市永和區秀朗路二段66巷9號2樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>巴赫納利亞台灣室內樂團</p>
          </td>
          <td>
            <p>黃義勛</p>
          </td>
          <td>
            <p>新北市永和區永平路218巷9號6樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺北大眾交響樂團</p>
          </td>
          <td>
            <p>黃素珠</p>
          </td>
          <td>
            <p>新北市永和區中和路499號16樓之1</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台北愛樂木管五重奏</p>
          </td>
          <td>
            <p>黃義敦</p>
          </td>
          <td>
            <p>新北市永和區永平路218巷9號8樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新北市青年交響樂團</p>
          </td>
          <td>
            <p>巫雪梨</p>
          </td>
          <td>
            <p>新北市永和區民生路46巷36號10樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>弦樂之音弦樂團</p>
          </td>
          <td>
            <p>黃冠勻</p>
          </td>
          <td>
            <p>新北市中和區興南路二段128巷7弄7號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>藝饗室內樂團</p>
          </td>
          <td>
            <p>王守芳</p>
          </td>
          <td>
            <p>新北市中和區景平路726之6號5樓之6</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>玉山菊元合奏團</p>
          </td>
          <td>
            <p>葛承澐</p>
          </td>
          <td>
            <p>新北市板橋區國光路189之5號5樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>轟工廠法國號重奏團</p>
          </td>
          <td>
            <p>蕭崇傑</p>
          </td>
          <td>
            <p>新北市板橋區光復街213號4樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>香頌室內樂團</p>
          </td>
          <td>
            <p>黃聖智</p>
          </td>
          <td>
            <p>新北市板橋區實踐路34號2樓</p>
          </td>
          <td>
            <a target="_" href="https://www.chansontpe.org/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>汲音集樂室內樂團</p>
          </td>
          <td>
            <p>吳錦雯</p>
          </td>
          <td>
            <p>新北市淡水區中山北路一段223號7樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺灣銅管樂團</p>
          </td>
          <td>
            <p>陳長伯</p>
          </td>
          <td>
            <p>新北市三重區中正南路248號11樓之7</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>亞洲青少年打擊樂團</p>
          </td>
          <td>
            <p>劉惠文</p>
          </td>
          <td>
            <p>新北市三重區五華街207號6樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>1980室內樂集</p>
          </td>
          <td>
            <p>蘇亦庠</p>
          </td>
          <td>
            <p>新北市三重區自強路三段42巷2之2號0918-051-867</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/1980室內樂集-384638105249121/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>惠文領袖打擊樂團</p>
          </td>
          <td>
            <p>劉惠文</p>
          </td>
          <td>
            <p>新北市三重區五華街207號6樓</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Wekids惠文藝術音樂學苑-279158329221905/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>雙子打擊樂團</p>
          </td>
          <td>
            <p>簡任廷</p>
          </td>
          <td>
            <p>新北市蘆洲區重陽街72之5號3樓</p>
          </td>
          <td>
            <a target="_" href="http://twincussion.com/intro">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>夢響管弦樂團</p>
          </td>
          <td>
            <p>楊陳德</p>
          </td>
          <td>
            <p>新北市蘆洲區民權路32號1樓</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/dreamphony">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>曼斯特低音銅管四重奏</p>
          </td>
          <td>
            <p>林昀宏</p>
          </td>
          <td>
            <p>0983-553-105</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/MLBQ2016/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>龍潭愛樂管弦樂團</p>
          </td>
          <td>
            <p>張鴻宇</p>
          </td>
          <td>
            <p>桃園市龍潭區公園路60號</p>
            <p>03-499-0111</p>
          </td>
          <td>
            <a target="_" href="http://www.ltpo.com.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>春之聲管弦樂團</p>
          </td>
          <td>
            <p>陳永清</p>
          </td>
          <td>
            <p>桃園市桃園區中正路1223號16樓</p>
            <p>03-331-5855</p>
          </td>
          <td>
            <a target="_" href="https://vsso.com.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>桃園愛樂管弦樂團</p>
          </td>
          <td>
            <p>黃子軒</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a href="mailto:jeffh.me83g@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>狂美交響管樂團</p>
          </td>
          <td>
            <p>謝韋民</p>
          </td>
          <td>
            <p>桃園市中壢區永福路1106號14樓</p>
            <p>03-285-0612</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/ConBello2017/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>桃園交響管樂團</p>
          </td>
          <td>
            <p>陳榮昇</p>
          </td>
          <td>
            <p>桃園市桃園區仁一街22號2樓</p>
            <p>0937-115-577</p>
          </td>
          <td>
            <a target="_" href="http://web.tysb.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>風動室內樂團</p>
          </td>
          <td>
            <p>鄭紘</p>
          </td>
          <td>
            <p>桃園市蘆竹區仁愛路二段3號16樓之5</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/windsoundensemble.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>S曼斯特低音重奏團</p>
          </td>
          <td>
            <p>林禮文</p>
          </td>
          <td>
            <p>桃園市楊梅區永寧路一巷19號9樓</p>
            <p>0983-553-105</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/SMLE2018/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>新竹交響管樂團</p>
          </td>
          <td>
            <p>李金恭</p>
          </td>
          <td>
            <p>新竹市北區北大路150號2樓</p>
            <p>03-545-6696</p>
          </td>
          <td>
            <a target="_" href="https://www.hcwo.net/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>巴雀藝術</p>
          </td>
          <td>
            <p>王若璇</p>
          </td>
          <td>
            <p>新竹縣竹北市嘉豐五路二段142號</p>
            <p>03-6683-642</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/bratsche.artist/">連結</a><br>
            <a target="_" href="https://www.bratsche.com.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>風城青少年管弦樂團</p>
          </td>
          <td>
            <p>吳明吉</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/風城青少年管弦樂團-144640359713791/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>國立臺灣交響樂團</p>
          </td>
          <td>
            <p>劉玄詠</p>
          </td>
          <td>
            <p>臺中市霧峰區中正路738之2號</p>
            <p>04-2339-1141</p>
          </td>
          <td>
            <a target="_" href="https://www.ntso.gov.tw/home">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>飛炫交響管樂團</p>
          </td>
          <td>
            <p>郭青樺</p>
          </td>
          <td>
            <p>臺中市西區華美街51巷8號1樓</p>
          </td>
          <td>
            <a href="mailto:kfhch@hotmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺灣青年管樂團</p>
          </td>
          <td>
            <p>陳玲玲</p>
          </td>
          <td>
            <p>臺中市霧峰區中正路1056巷21號</p>
            <p>0963-129-038</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwanyouthband/">連結</a><br>
            <a href="mailto:taiwanyouthband@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>綺想木笛室內樂團</p>
          </td>
          <td>
            <p>郭焜照</p>
          </td>
          <td>
            <p>臺中市豐原區南陽里安康路20巷39弄1號</p>
            <p>04-2529-4863</p>
          </td>
          <td>
            <a href="mailto:recorder.capriccio@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>古典管絃樂團</p>
          </td>
          <td>
            <p>曾慶然</p>
          </td>
          <td>
            <p>臺中市西屯區市政北二路400號</p>
            <p>0928-956-716</p>
          </td>
          <td>
            <a target="_" href="http://www.classic-orch.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>青响樂集</p>
          </td>
          <td>
            <p>林佳慧</p>
          </td>
          <td>
            <p>臺中市潭子區潭陽里福潭路582號5樓</p>
            <p>0932-040-017</p>
          </td>
          <td>
            <a href="mailto:iamdindon@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>拾音樂集</p>
          </td>
          <td>
            <p>陳怡均</p>
          </td>
          <td>
            <p>臺中市北區學士路187號10樓</p>
            <p>0932-455-901</p>
          </td>
          <td>
            <a href="mailto:chenlovemusic@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>橙樂管弦樂團</p>
          </td>
          <td>
            <p>曾鵬宇</p>
          </td>
          <td>
            <p>臺中市霧峰區中正路1056巷21號</p>
          </td>
          <td>
            <a href="mailto:OrangeOrchestra2007@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>維也納室內樂團</p>
          </td>
          <td>
            <p>鄭翰添</p>
          </td>
          <td>
            <p>臺中市北屯區綏遠路二段180號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>福爾摩沙愛樂管絃樂團</p>
          </td>
          <td>
            <p>陳玫君</p>
          </td>
          <td>
            <p>臺中市北屯區水景里景和街262號1樓</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/FormosaPhilharmonic/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台中市交響樂團</p>
          </td>
          <td>
            <p>張淑儀</p>
          </td>
          <td>
            <p>臺中市西區五權西路一段237號8樓之2</p>
            <p>04-2378-7838</p>
          </td>
          <td>
            <a target="_" href="http://www.t-cso.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>幾個人室內樂團</p>
          </td>
          <td>
            <p>陳宜彣</p>
          </td>
          <td>
            <p>臺中市西區英才路589巷2號6樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>奏出福爾摩沙室內樂團</p>
          </td>
          <td>
            <p>江瑜庭</p>
          </td>
          <td>
            <p>臺中市沙鹿區福興里福成路68巷76號</p>
            <p>0905-827-997</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>構響室內樂團</p>
          </td>
          <td>
            <p>謝宛軒</p>
          </td>
          <td>
            <p>臺中市霧峰區振興街21號11樓之1</p>
            <p>0963-129-037</p>
          </td>
          <td>
            <a href="mailto:composetrio@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣銅管五重奏團</p>
          </td>
          <td>
            <p>林怡文</p>
          </td>
          <td>
            <p>臺中市北區太原北路10號1樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新藝銅管五重奏</p>
          </td>
          <td>
            <p>劉宛貞</p>
          </td>
          <td>
            <p>臺中市霧峰區樹仁路121巷2號10樓之5</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台中長笛室內樂團</p>
          </td>
          <td>
            <p>許仁忠</p>
          </td>
          <td>
            <p>臺中市北區中清路一段726巷13號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>古典管絃樂團</p>
          </td>
          <td>
            <p>曾慶然</p>
          </td>
          <td>
            <p>臺中市南屯區向心路107巷5號</p>
            <p>04-2380-6616</p>
          </td>
          <td>
            <a href="mailto:classic.orch@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>極限打擊二重奏</p>
          </td>
          <td>
            <p>黃英哲</p>
          </td>
          <td>
            <p>臺中市太平區振英街106巷6號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台中愛樂管絃樂團</p>
          </td>
          <td>
            <p>唐旦祥</p>
          </td>
          <td>
            <p>臺中市南區復興路二段87之1號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>聆音室內樂團</p>
          </td>
          <td>
            <p>許芳瑛</p>
          </td>
          <td>
            <p>臺中市南區忠明南路782號6樓之2</p>
            <p>04-2265-1860</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>員林愛樂</p>
          </td>
          <td>
            <p>張博銘</p>
          </td>
          <td>
            <p>彰化縣員林市育英路567號</p>
            <p>04-834-7485</p>
          </td>
          <td>
            <a target="_" href="https://baishamus.weebly.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>彰化青年管樂團</p>
          </td>
          <td>
            <p>林垂正</p>
          </td>
          <td>
            <p>彰化縣芬園鄉大埔村德興路一段129號</p>
            <p>0931-581-755</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>彰化愛樂室內樂團</p>
          </td>
          <td>
            <p>蕭亦翎</p>
          </td>
          <td>
            <p>彰化縣彰化市中山路二段437號3樓</p>
            <p>04-728-7972</p>
          </td>
          <td>
            <a href="mailto:phiharmonia.changhua.tw@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>就是木笛室內樂團</p>
          </td>
          <td>
            <p>邱聖育</p>
          </td>
          <td>
            <p>彰化縣埔心鄉仁里村仁三路93巷8號</p>
            <p>04-828-2011</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>親愛愛樂</p>
          </td>
          <td>
            <p>王子建</p>
          </td>
          <td>
            <p>南投縣仁愛鄉親愛村高平路3號</p>
            <p>049-2974-590</p>
          </td>
          <td>
            <a target="_" href="https://www.chin-ai.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>雲林愛樂室內樂團</p>
          </td>
          <td>
            <p>楊正治</p>
          </td>
          <td>
            <p>雲林縣斗六市永樂街27之2號</p>
            <p>05-532-4860</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>正心愛樂管弦樂團</p>
          </td>
          <td>
            <p>鄭弘藝</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/SHPO.Music/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>絕響室內樂團</p>
          </td>
          <td>
            <p>林宇欣</p>
          </td>
          <td>
            <p>雲林縣斗六市溪洲里中南路290巷9弄61號</p>
            <p>0970-010-551</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>Muse Trio繆斯三重奏</p>
          </td>
          <td>
            <p>張嘉玲</p>
          </td>
          <td>
            <p>雲林縣斗六市嘉東南路56巷12號</p>
            <p>05-537-3919</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>雲林縣薩克斯風管樂團</p>
          </td>
          <td>
            <p>許平和</p>
          </td>
          <td>
            <p>雲林縣虎尾鎮平和里青埔2號之15</p>
            <p>0932-588-329</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>陽光室內樂團</p>
          </td>
          <td>
            <p>廖婉君</p>
          </td>
          <td>
            <p>雲林縣斗六市鎮南路82之1號</p>
            <p>0919-011-777</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>嘉義市管樂團</p>
          </td>
          <td>
            <p>陳建州</p>
          </td>
          <td>
            <p>嘉義市東區泰安里忠孝路275號</p>
            <p>05-222-5173</p>
          </td>
          <td>
            <a href="mailto:cywo@ms14.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>嘉義交響管樂團</p>
          </td>
          <td>
            <p>高于仁</p>
          </td>
          <td>
            <p>嘉義市西區民生南路118之1號</p>
            <p>05-216-2762</p>
          </td>
          <td>
            <a href="mailto:lifetime@ms12.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>嘉義市青年管弦樂團</p>
          </td>
          <td>
            <p>陳雍杰</p>
          </td>
          <td>
            <p>嘉義市東區豐年里吳鳳南路32巷23號</p>
            <p>0926-330-786</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>嘉義縣愛樂木笛合奏團</p>
          </td>
          <td>
            <p>簡文智</p>
          </td>
          <td>
            <p>嘉義縣大林鎮西林里中正路423號</p>
            <p>05-265-2061</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>樸城弦樂團</p>
          </td>
          <td>
            <p>林上棋</p>
          </td>
          <td>
            <p>嘉義縣朴子市四維路三段316號</p>
            <p>05-370-6054</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>涴莎室內樂團</p>
          </td>
          <td>
            <p>陳室融</p>
          </td>
          <td>
            <p>臺南市東區東門路二段167巷16弄12號</p>
            <p>0929-048-109</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺南市管樂團</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>臺南市新化區信義路142之1（新化演藝廳）</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tsbandsh/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>夢想田室內樂團</p>
          </td>
          <td>
            <p>張怡婷</p>
          </td>
          <td>
            <p>臺南市安南區海中街300號</p>
            <p>0920-026-192</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺灣玉山交響樂團</p>
          </td>
          <td>
            <p>許恕藍</p>
          </td>
          <td>
            <p>臺南市中西區青年里青年路47巷10號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺邦獨奏家樂團</p>
          </td>
          <td>
            <p>陳依萱</p>
          </td>
          <td>
            <p>臺南市安平區永華二街199號2樓</p>
            <p>06-293-1790</p>
          </td>
          <td>
            <a target="_" href="http://www.tso.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台南愛樂管絃樂團</p>
          </td>
          <td>
            <p>唐旦祥</p>
          </td>
          <td>
            <p>臺南市東區崇信街18號</p>
            <p>0929-118-866</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台灣藝術家交響樂團</p>
          </td>
          <td>
            <p>呂景民</p>
          </td>
          <td>
            <p>臺南市東區立德一路1巷10號1樓</p>
            <p>06-703-5353</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>自由人室內樂團</p>
          </td>
          <td>
            <p>王文娟</p>
          </td>
          <td>
            <p>臺南市中西區五妃街76號6樓之2</p>
            <p>06-282-7469</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>高雄藝曲愛樂管樂團</p>
          </td>
          <td>
            <p>楊子霆</p>
          </td>
          <td>
            <p>0939-255-544</p>
          </td>
          <td>
            <a href="mailto:kamwb20150412@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄市交響樂團</p>
          </td>
          <td>
            <p>楊智欽</p>
          </td>
          <td>
            <p>高雄市鳳山區光遠路161號</p>
            <p>07-743-6633</p>
          </td>
          <td>
            <a target="_" href="http://kpcaf.khcc.gov.tw/index.php?temp=kso&amp;lang=cht">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣旋轉木馬古樂團</p>
          </td>
          <td>
            <p>盧玥綝</p>
          </td>
          <td>
            <p>高雄市鳳山區三商街1巷2弄3之2號</p>
            <p>0975-583-567</p>
          </td>
          <td>
            <a href="mailto:earlymusiccarousel@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>弓爵大提琴室內樂團</p>
          </td>
          <td>
            <p>蘇逸凌</p>
          </td>
          <td>
            <p>高雄市鳳山區濱山街1號6樓之4</p>
            <p>0928-838-325</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/GongJueDaTiQinShiNeiLeTuan">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>薪傳打擊樂團</p>
          </td>
          <td>
            <p>鄭翔夫</p>
          </td>
          <td>
            <p>高雄市三民區大豐二路116之8號2樓</p>
            <p>07-385-5641</p>
          </td>
          <td>
            <a href="mailto:succperc1995@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>新古典室內樂團</p>
          </td>
          <td>
            <p>陳欣宜</p>
          </td>
          <td>
            <p>高雄市三民區建國三路495號9樓之3</p>
            <p>07-282-8496</p>
          </td>
          <td>
            <a href="mailto:godspeed0304@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>漫遊者室內樂團</p>
          </td>
          <td>
            <p>黃子宜</p>
          </td>
          <td>
            <p>高雄市三民區禮明路70號</p>
            <p>07-385-2585</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/漫遊者室內樂團-The-Wanderer-Chamber-Ensemble-234407220317636/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>佳音室內樂團</p>
          </td>
          <td>
            <p>陳一萱</p>
          </td>
          <td>
            <p>高雄市三民區河堤路510之3號7樓</p>
            <p>07-341-1356</p>
          </td>
          <td>
            <a href="mailto:chiayin2014@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>對位室內樂團</p>
          </td>
          <td>
            <p>林怡雯</p>
          </td>
          <td>
            <p>高雄市新興區中正二路218號4樓之5</p>
            <p>07-226-0989</p>
          </td>
          <td>
            <a target="_" href="http://www.counterpoint.org.tw/">連結</a><br>
            <a href="mailto:tw.counterpoint@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Dominant5鋼琴五重奏室內樂團</p>
          </td>
          <td>
            <p>康郁理</p>
          </td>
          <td>
            <p>高雄市新興區民權一路251號27樓</p>
            <p>0919-774-516</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Dominant5-102445478056031/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>One Punch Contemporary Chamber Ensemble當代室內樂團</p>
          </td>
          <td>
            <p>李茂嵩</p>
          </td>
          <td>
            <p>高雄市新興區八德一路335號5樓</p>
          </td>
          <td>
            <a href="mailto:op.maosunglee@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>福爾摩沙巴洛克古樂團</p>
          </td>
          <td>
            <p>陳逸芬</p>
          </td>
          <td>
            <p>高雄市新興區新興路29號2樓</p>
            <p>0911-163-707</p>
          </td>
          <td>
            <a target="_" href="http://www.formosabaroque.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>巴赫納利亞台灣室內樂團．高雄</p>
          </td>
          <td>
            <p>黃意雯</p>
          </td>
          <td>
            <p>高雄市新興區復興一路10號7樓之5</p>
            <p>02-2922-6131</p>
          </td>
          <td>
            <a href="mailto:bachanaliataiwan@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄之音管樂團</p>
          </td>
          <td>
            <p>孫炳剛</p>
          </td>
          <td>
            <p>高雄市苓雅區苓中路191號5樓</p>
            <p>0920-559-970</p>
          </td>
          <td>
            <a href="mailto:sokwe.org@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣獨奏家交響樂團</p>
          </td>
          <td>
            <p>陳冠斌</p>
          </td>
          <td>
            <p>高雄市苓雅區五福一路77號10樓之1</p>
            <p>07-225-4100</p>
          </td>
          <td>
            <a target="_" href="http://www.taiwansoloists.org">連結</a><br>
            <a href="mailto:info@cmiam.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>雄頌管弦樂團</p>
          </td>
          <td>
            <p>周安瑞</p>
          </td>
          <td>
            <p>高雄市苓雅區林泉街23號<br>07-724-8759</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/siungsongorch">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Miracle長笛明星樂團</p>
          </td>
          <td>
            <p>林文苑</p>
          </td>
          <td>
            <p>高雄市左營區太華街70號</p>
            <p>07-559-1067</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Miracleflute/">連結</a><br>
            <a href="mailto:fl.miracle@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>發條貓造音集</p>
          </td>
          <td>
            <p>郭純杏</p>
          </td>
          <td>
            <p>高雄市左營區安吉街438號4樓之2</p>
            <p>0985-350-012</p>
          </td>
          <td>
            <a href="mailto:clockworkingcat@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>絢季室內樂團</p>
          </td>
          <td>
            <p>曾瀞瑩</p>
          </td>
          <td>
            <p>高雄市左營區至真路155號7樓之2</p>
            <p>07-347-8342</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/SplendorChamberMusic/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>極地之光管弦樂團</p>
          </td>
          <td>
            <p>杜紹堯</p>
          </td>
          <td>
            <p>高雄市左營區新莊一路135號7樓之3</p>
            <p>0938-518-518</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/apex.orchestra/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄市管樂團</p>
          </td>
          <td>
            <p>沈銘彥</p>
          </td>
          <td>
            <p>高雄市前鎮區一心二路157號12樓1205室</p>
            <p>07-715-6611</p>
          </td>
          <td>
            <a href="mailto:kcwo2012@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>巴洛克獨奏家樂團</p>
          </td>
          <td>
            <p>葉懿萱</p>
          </td>
          <td>
            <p>高雄市鼓山區美術北一街63號</p>
            <p>07-525-1556</p>
          </td>
          <td>
            <a target="_" href="http://www.baroque-camerata.org/">連結</a><br>
            <a href="mailto:kmu021013@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>藝綻室內樂團</p>
          </td>
          <td>
            <p>温依婷</p>
          </td>
          <td>
            <p>高雄市鼓山區華泰路145號</p>
            <p>07-554-1797</p>
          </td>
          <td>
            <a href="mailto:artsblooming@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>六藝樂集</p>
          </td>
          <td>
            <p>沈銘彥</p>
          </td>
          <td>
            <p>高雄市前鎮區和義街121號</p>
            <p>07-715-6611</p>
          </td>
          <td>
            <a href="mailto:sixartsmusic@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>繆思室內樂團</p>
          </td>
          <td>
            <p>黃惠鈴</p>
          </td>
          <td>
            <p>高雄市前鎮區廣州三街351號</p>
            <p>0930-818-040</p>
          </td>
          <td>
            <a href="mailto:onaip1017@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣愛樂室內樂團</p>
          </td>
          <td>
            <p>吳佳鴻</p>
          </td>
          <td>
            <p>高雄市前鎮區三多三路137號7樓之1</p>
            <p>07-332-7006</p>
          </td>
          <td>
            <a href="mailto:sonatarecord@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺灣吹笛人室內樂團</p>
          </td>
          <td>
            <p>凌珮瑄</p>
          </td>
          <td>
            <p>高雄市前鎮區管仲南路346號</p>
            <p>0988-530-086</p>
          </td>
          <td>
            <a href="mailto:irisma313@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>悠然弦樂團</p>
          </td>
          <td>
            <p>林鴻喻</p>
          </td>
          <td>
            <p>高雄市前鎮區衡山街76號</p>
            <p>07-537-2008</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>高雄室內重奏團</p>
          </td>
          <td>
            <p>張原碩</p>
          </td>
          <td>
            <p>高雄市旗山區樹人路43之9號</p>
            <p>07-662-3208</p>
          </td>
          <td>
            <a href="mailto:kce.taiwan@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>捍衛音樂工作坊</p>
          </td>
          <td>
            <p>陳聖昱</p>
          </td>
          <td>
            <p>高雄市鼓山區文信路257號10樓</p>
            <p>0955-215-877</p>
          </td>
          <td>
            <a href="mailto:defendyourself2018@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>彈指之間室內樂團</p>
          </td>
          <td>
            <p>洪寅洲</p>
          </td>
          <td>
            <p>高雄市鹽埕區必忠街170號</p>
            <p>07-521-4731</p>
          </td>
          <td>
            <a href="mailto:yh002e@yahoo.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>他拉喇叭團</p>
          </td>
          <td>
            <p>王怡人</p>
          </td>
          <td>
            <p>高雄市鳥松區松埔北巷4之40號6樓</p>
            <p>0908-217-568</p>
          </td>
          <td>
            <a href="mailto:yijenwang@tlbebrass.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>龍泉愛樂</p>
          </td>
          <td>
            <p>吳淑如</p>
          </td>
          <td>
            <p>屏東縣內埔鄉昌南路1巷9號</p>
            <p>0956-610-621</p>
          </td>
          <td>
            <a href="mailto:sj_5512@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>繆思室內樂團</p>
          </td>
          <td>
            <p>許晉怡</p>
          </td>
          <td>
            <p>屏東縣屏東市林森路東四段10號</p>
            <p>08-722-0635</p>
          </td>
          <td>
            <a href="mailto:chinyihsu@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>音緣樂集室內樂團</p>
          </td>
          <td>
            <p>葉乃菁</p>
          </td>
          <td>
            <p>屏東縣屏東市豐榮里民強街3號9樓</p>
            <p>0939-097-296</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>屏東聯合管樂團</p>
          </td>
          <td>
            <p>張詠佑</p>
          </td>
          <td>
            <p>屏東縣屏東市瑞光路二段236號</p>
            <p>0912-777-479</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/ptsb1995/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東縣管弦樂團</p>
          </td>
          <td>
            <p>曾令凱</p>
          </td>
          <td>
            <p>0921-250-966</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/ptso2016/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東縣交響樂團</p>
          </td>
          <td>
            <p>陳明雄</p>
          </td>
          <td>
            <p>屏東縣屏東市瑞光路二段236號</p>
            <p>08-737-2099</p>
          </td>
          <td>
            <a href="mailto:fanfare2099@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東愛樂室內樂團</p>
          </td>
          <td>
            <p>江敬業</p>
          </td>
          <td>
            <p>屏東縣屏東市廣東路1550號</p>
            <p>0910-966-988</p>
          </td>
          <td>
            <a href="mailto:p7517777@xuite.hinet.net">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>漫響室內樂團</p>
          </td>
          <td>
            <p>鄭羽捷</p>
          </td>
          <td>
            <p>宜蘭縣羅東鎮林森路154之1號</p>
            <p>0952-003-877</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/muzik2014tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>宜蘭節慶室內樂團</p>
          </td>
          <td>
            <p>黃啟信</p>
          </td>
          <td>
            <p>宜蘭縣宜蘭市新興路209號</p>
            <p>0933-046-547</p>
          </td>
          <td>
            <a href="mailto:trbarts2004@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>行樂愛樂室內樂團</p>
          </td>
          <td>
            <p>吳茵茵</p>
          </td>
          <td>
            <p>宜蘭縣羅東鎮大新里站前路32之2號5樓</p>
            <p>0963-131-252</p>
          </td>
          <td>
            <a href="mailto:singyue.music@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>宜蘭青年管樂團</p>
          </td>
          <td>
            <p>林緯</p>
          </td>
          <td>
            <p>宜蘭縣壯圍鄉吉祥村壯五路277號</p>
            <p>0981-341-834</p>
          </td>
          <td>
            <a href="mailto:f902601@hotmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>蘭陽人銅管五重奏</p>
          </td>
          <td>
            <p>吳倍瑄</p>
          </td>
          <td>
            <p>宜蘭縣羅東鎮建國街33號</p>
            <p>0914-034-039</p>
          </td>
          <td>
            <a href="mailto:deannawu88@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>蘭陽管樂團</p>
          </td>
          <td>
            <p>林小姐</p>
          </td>
          <td>
            <p>宜蘭縣宜蘭市中山路二段482號</p>
            <p>03-936-9115 #115</p>
          </td>
          <td>
            <a href="mailto:yilanperform@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>宜蘭愛樂管弦樂團</p>
          </td>
          <td>
            <p>謝元富</p>
          </td>
          <td>
            <p>宜蘭縣礁溪鄉林美村林尾路160號</p>
            <p>0911-659-343</p>
          </td>
          <td>
            <a href="mailto:shiehyf@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>花蓮管樂團</p>
          </td>
          <td>
            <p>蔡文貴</p>
          </td>
          <td>
            <p>0988-517-389</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>聲子樂集</p>
          </td>
          <td>
            <p>林希哲</p>
          </td>
          <td>
            <p>花蓮縣花蓮市博愛街199號</p>
            <p>03-832-4517</p>
          </td>
          <td>
            <a target="_" href="https://phononmusic.wordpress.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>洄瀾室內樂團</p>
          </td>
          <td>
            <p>武崢</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a href="mailto:2013hco@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>High FLY豎笛四重奏</p>
          </td>
          <td>
            <p>范捷安</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/High-Fly豎笛四重奏-1501783193374355/about/?ref=page_internal">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>聲根室內樂團</p>
          </td>
          <td>
            <p>劉環瑜</p>
          </td>
          <td>
            <p>0988-517-389</p>
          </td>
          <td>
            <a href="mailto:Liuhuanyu11@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>禾弦愛樂樂團</p>
          </td>
          <td>
            <p>紀夙育</p>
          </td>
          <td>
            <p>花蓮縣玉里鎮仁愛路一段256號</p>
            <p>03-888-0185</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台東回響樂團</p>
          </td>
          <td>
            <p>廖逸芬</p>
          </td>
          <td>
            <p>089-228-1678</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TTechoOrchestra">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>菊之音管絃樂團</p>
          </td>
          <td>
            <p>柯仲甫</p>
          </td>
          <td>
            <p>澎湖縣馬公市光復路185之3號</p>
            <p>0933-373-285</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>菊之音打擊樂團</p>
          </td>
          <td>
            <p>柯仲甫</p>
          </td>
          <td>
            <p>澎湖縣馬公市光復路185之3號</p>
            <p>0933-373-287</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>菊之音木笛合奏團</p>
          </td>
          <td>
            <p>柯仲甫</p>
          </td>
          <td>
            <p>澎湖縣馬公市光復路185之3號</p>
            <p>0933-373-289</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>小星辰鋼琴三重奏</p>
          </td>
          <td>
            <p>陳星妤</p>
          </td>
          <td>
            <p>澎湖縣馬公市民權路89號</p>
            <p>0982-492-112</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>金門絃樂四重奏團</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://reurl.cc/WDRXD">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>CPE鋼琴重奏團</p>
          </td>
          <td>
            <p>簡雪豐</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/Crossplay-Piano-Ensemble-鋼琴重奏團-281325146895/">連結</a>
          </td>
        </tr>
      </tbody>
    </table>
    <br />
    <h3>二、合唱團</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>雨韻合唱團</p>
          </td>
          <td>
            <p>陳建宏</p>
          </td>
          <td>
            <p>基隆市安樂區樂利三街205號7樓</p>
            <p>02-2425-3518</p>
          </td>
          <td>
            <a target="_" href="http://www.yuyun.org.tw/yuyun/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>啄木鳥合唱團</p>
          </td>
          <td>
            <p>陳吉宗</p>
          </td>
          <td>
            <p>基隆市仁愛區仁二路85號</p>
            <p>02-2423-4884</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/基隆市啄木鳥合唱團粉絲團-516315805193598">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>基隆市愛樂合唱團</p>
          </td>
          <td>
            <p>莊瑾潔</p>
          </td>
          <td>
            <p>基隆市仁愛區仁二路119巷13之4號1樓</p>
            <p>02-2425-5289</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/KeelungPhilharmonicChoir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>新韻合唱團</p>
          </td>
          <td>
            <p>溫呈祥</p>
          </td>
          <td>
            <p>基隆市七堵區崇義街128號</p>
            <p>0980-712-734</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>龤之聲男聲合唱團</p>
          </td>
          <td>
            <p>陳建豪</p>
          </td>
          <td>
            <p>基隆市安樂區八德路31巷8號</p>
            <p>0933-935-303</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/hsieh.jsc/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Vocal Asia人聲樂集</p>
          </td>
          <td>
            <p>陳午明</p>
          </td>
          <td>
            <p>臺北市中正區忠孝東路一段35號11樓</p>
            <p>02-3393-1211</p>
          </td>
          <td>
            <a target="_" href="https://www.vocalasia.com/index.php?lang=tw">連結</a><br>
            <a href="mailto:info@vocalasia.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>蔚藍之聲合唱團</p>
          </td>
          <td>
            <p>潘宇文</p>
          </td>
          <td>
            <p>臺北市中正區羅斯福路四段162號4樓</p>
            <p>02-2365-8943</p>
          </td>
          <td>
            <a target="_" href="http://lavoixdazur.blogspot.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>大地之歌藝術聯盟</p>
          </td>
          <td>
            <p>黃世傑</p>
          </td>
          <td>
            <p>臺北市中正區詔安街26巷6號1樓</p>
            <p>0933-701-390</p>
          </td>
          <td>
            <a href="mailto:aasote@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北世紀合唱團</p>
          </td>
          <td>
            <p>郭英調</p>
          </td>
          <td>
            <p>臺北市北投區石牌路二段325巷5號2樓</p>
            <p>0920-592-810</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TaipeiCenturyChoir">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>金穗合唱團</p>
          </td>
          <td>
            <p>于國藩</p>
          </td>
          <td>
            <p>臺北市大安區永康街41巷5號</p>
            <p>0972-101-106</p>
          </td>
          <td>
            <a href="mailto:9508b2@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台大合唱團</p>
          </td>
          <td>
            <p>林品瑢</p>
          </td>
          <td>
            <p>臺北市大安區羅斯福路四段85號</p>
            <p>0952-790-068</p>
          </td>
          <td>
            <a href="mailto:ntuchorusone@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>尋人啟事人聲樂團</p>
          </td>
          <td>
            <p>劉靜諭</p>
          </td>
          <td>
            <p>臺北市大安區復興南路一段107巷5弄18號</p>
          </td>
          <td>
            <a href="mailto:lcy6667@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北室內合唱團</p>
          </td>
          <td>
            <p>陳雲紅</p>
          </td>
          <td>
            <p>臺北市大安區敦化南路一段159號</p>
            <p>02-2776-4089</p>
          </td>
          <td>
            <a target="_" href="www.tcschoir.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>木樓合唱團</p>
          </td>
          <td>
            <p>吳嘉和</p>
          </td>
          <td>
            <p>臺北市大安區龍淵里和平東路二段96巷17弄6號</p>
            <p>02-2365-8943</p>
          </td>
          <td>
            <a target="_" href="http://www.muller.org.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>G大調男聲合唱團</p>
          </td>
          <td>
            <p>李鴻偉</p>
          </td>
          <td>
            <p>臺北市大安區和平東路一段163號7樓</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/gMajortw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北漢聲合唱團</p>
          </td>
          <td>
            <p>洪綺玲</p>
          </td>
          <td>
            <p>臺北市大安區忠孝東路三段229之6號4樓</p>
            <p>02-2751-0191</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>幕聲合唱團</p>
          </td>
          <td>
            <p>楊艾玲</p>
          </td>
          <td>
            <p>0928-655-397</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/tabernacle.choir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北心聲合唱團</p>
          </td>
          <td>
            <p>劉紹棟</p>
          </td>
          <td>
            <p>臺北市中山區北安路589號5樓</p>
            <p>02-2702-5252</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taipeiharmonicchorus/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>福爾摩沙合唱團</p>
          </td>
          <td>
            <p>蘇慶俊</p>
          </td>
          <td>
            <p>臺北市中山區民權東路二段61號2樓</p>
            <p>02-2591-9422</p>
          </td>
          <td>
            <a target="_" href="http://formosasingers.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>福爾摩沙不惑之聲合唱團</p>
          </td>
          <td>
            <p>周義山</p>
          </td>
          <td>
            <p>臺北市中山區民權東路二段59號2樓</p>
            <p>02-2591-9422</p>
          </td>
          <td>
            <a href="mailto:a4ssingers@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北當代合唱團</p>
          </td>
          <td>
            <p>戴怡音</p>
          </td>
          <td>
            <p>臺北市南港區南港路三段356號</p>
            <p>0910-229-300</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tccchoir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>拉縴人藝象女聲合唱團</p>
          </td>
          <td>
            <p>洪晴瀠</p>
          </td>
          <td>
            <p>新北市新店區北新路三段205之3號7樓B室</p>
            <p>02-8913-2068</p>
          </td>
          <td>
            <a target="_" href="http://www.tmccaf.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>拉縴人風雅頌合唱團</p>
          </td>
          <td>
            <p>楊巧晴</p>
          </td>
          <td>
            <p>新北市新店區北新路三段205之3號7樓B室</p>
            <p>02-8913-2068</p>
          </td>
          <td>
            <a target="_" href="http://www.tmccaf.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>拉縴人青年合唱團</p>
          </td>
          <td>
            <p>賴建邑</p>
          </td>
          <td>
            <p>新北市新店區北新路三段205之3號7樓B室</p>
            <p>02-8913-2069</p>
          </td>
          <td>
            <a target="_" href="http://www.tmccaf.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Sirens人聲樂團</p>
          </td>
          <td>
            <p>官文琪</p>
          </td>
          <td>
            <p>新北市三峽區復興路160巷2弄7 號5樓</p>
            <p>0929-356-282</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/acasirens">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺北華新兒童合唱團</p>
          </td>
          <td>
            <p>方素貞</p>
          </td>
          <td>
            <p>新北市板橋區文化路二段90號地下1樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>大地五重唱</p>
          </td>
          <td>
            <p>黃大城</p>
          </td>
          <td>
            <p>新北市新店區大豐路80號4樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>青韵合唱團</p>
          </td>
          <td>
            <p>張成璞</p>
          </td>
          <td>
            <p>新北市新店區順安街4號</p>
            <p>02-2771-1270</p>
          </td>
          <td>
            <a target="_" href="https://www.chinyun.org.tw">連結</a><br>
            <a href="mailto:chingyunchoir@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>新韻合唱團</p>
          </td>
          <td>
            <p>游安芸</p>
          </td>
          <td>
            <p>新北市新店區北新路一段64巷12弄3號2樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>八角塔男聲合唱團</p>
          </td>
          <td>
            <p>鄭睦群</p>
          </td>
          <td>
            <p>新北市淡水區新民街120巷9號7樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蝦米視障人聲樂團</p>
          </td>
          <td>
            <p>朱元雷</p>
          </td>
          <td>
            <p>臺北市內湖區麗山里內湖路一段387巷5號</p>
            <p>02-2920-9028</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/shiamishiami/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>桃園知音合唱團</p>
          </td>
          <td>
            <p>陳台琦</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/TaoYuanChoirOfJoy/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>星穎藝術合唱團</p>
          </td>
          <td>
            <p>陳銘達</p>
          </td>
          <td>
            <p>桃園市桃園區泰昌九街28號</p>
            <p>0920-919-655</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/singing2gether">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>歐開合唱團</p>
          </td>
          <td>
            <p>賴家慶</p>
          </td>
          <td>
            <p>0958-137-281</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/okaisingers/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>沂風女聲室內合唱團</p>
          </td>
          <td>
            <p>李寶鈺</p>
          </td>
          <td>
            <p>新竹市東區中華路二段270號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/YiPhoneChamberChoir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>心築愛樂合唱團</p>
          </td>
          <td>
            <p>張筱琪</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新竹市立混聲合唱團</p>
          </td>
          <td>
            <p>徐鴻慶</p>
          </td>
          <td>
            <p>新竹市北區中央路109號（新竹市文化局）<br>03-591-0389</p>
          </td>
          <td>
            <a href="mailto:sibonnevie@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>海鷗．K人聲樂團</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/seagullk.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>晶晶兒童合唱團</p>
          </td>
          <td>
            <p>朱娟瑩</p>
          </td>
          <td>
            <p>新竹市東區工業東二路1號4樓407室</p>
          </td>
          <td>
            <a target="_" href="http://www.crystalchoir.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>竹友混聲合唱團</p>
          </td>
          <td>
            <p>吳和蘭</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/ZhuyouMixedChoir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>黃桂志客家合唱團</p>
          </td>
          <td>
            <p>黃桂志</p>
          </td>
          <td>
            <p>苗栗縣頭份市五福街2號4樓</p>
            <p>03-767-5101</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>郭芝苑室內合唱團</p>
          </td>
          <td>
            <p>阮文池</p>
          </td>
          <td>
            <p>苗栗縣苑裡鎮海岸里46之1號</p>
            <p>037-864-787</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台中室內合唱團</p>
          </td>
          <td>
            <p>王政義</p>
          </td>
          <td>
            <p>臺中市南區忠明南路801號9樓之3</p>
            <p>0978-589-019</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TaichungChamberChoir">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台中藝術家室內合唱團</p>
          </td>
          <td>
            <p>莊璧華</p>
          </td>
          <td>
            <p>臺中市南區三民西路357號6樓</p>
          </td>
          <td>
            <a target="_" href="http://taichungartistchoir.com/about-us/about-tacc">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺中琴瑟合唱團</p>
          </td>
          <td>
            <p>酈長春</p>
          </td>
          <td>
            <p>臺中市北區進化路589之13號14樓</p>
            <p>04-2238-8203</p>
          </td>
          <td>
            <a href="mailto:lcc36419@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>愛唱歌手合唱團</p>
          </td>
          <td>
            <p>林慧芬</p>
          </td>
          <td>
            <p>臺中市北區東漢街9號2樓之3</p>
            <p>0982-918-508</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/sstaichung">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>靜宸合唱團</p>
          </td>
          <td>
            <p>徐麗蘭</p>
          </td>
          <td>
            <p>臺中市北區青島路三段140號12樓之6</p>
          </td>
          <td>
            <a href="mailto:dcviolet2011@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>天一合唱團</p>
          </td>
          <td>
            <p>賴科宏</p>
          </td>
          <td>
            <p>臺中市大里區益民路二段347號</p>
            <p>04-2481-5911</p>
          </td>
          <td>
            <a href="mailto:tienyichorus@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台中市新世紀合唱團</p>
          </td>
          <td>
            <p>鄭家齊</p>
          </td>
          <td>
            <p>臺中市西屯區福林路480號7樓之1</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/NEWERACHORUS/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>線性室內樂</p>
          </td>
          <td>
            <p>周尚樺</p>
          </td>
          <td>
            <p>臺中市后里區眉山里公安路322號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/linearchamber/?ref=page_internallinearchamber@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>濤韻男聲合唱團</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/manlodymalesingers/">連結</a><br>
            <a href="mailto:manlodymalesingers@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>雅音合唱團</p>
          </td>
          <td>
            <p>黃華芬</p>
          </td>
          <td>
            <p>彰化縣員林鎮員水路二段482號</p>
            <p>04-832-4479</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>彰化市愛樂合唱團</p>
          </td>
          <td>
            <p>蘇哲雄</p>
          </td>
          <td>
            <p>彰化縣彰化市永興街95號</p>
            <p>04-722-6077</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>雲林愛樂室內合唱團</p>
          </td>
          <td>
            <p>許淑媛</p>
          </td>
          <td>
            <p>雲林縣虎尾鎮林森路一段396巷1弄2號</p>
            <p>05-532-5607</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/雲林愛樂室內合唱團-162104895425/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>嘉義室內合唱團</p>
          </td>
          <td>
            <p>黃黑汶</p>
          </td>
          <td>
            <p>嘉義市東區維新路259號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Chiayi.Chamber.Choir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>嘉義愛樂合唱團</p>
          </td>
          <td>
            <p>鍾秀華</p>
          </td>
          <td>
            <p>嘉義市西區忠義街197巷8號</p>
          </td>
          <td>
            <a href="mailto:mama340217@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>嘉義男聲合唱團</p>
          </td>
          <td>
            <p>曾維民</p>
          </td>
          <td>
            <p>嘉義市東區五福街131巷20號</p>
            <p>05-277-8577</p>
          </td>
          <td>
            <a href="mailto:nicola2031@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台南室內合唱團</p>
          </td>
          <td>
            <p>朱忠宏</p>
          </td>
          <td>
            <p>臺南市東區裕農路27之1號3樓之2</p>
            <p>0919-023-235</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tainanchamber/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>成大校友合唱團</p>
          </td>
          <td>
            <p>朱銘祥</p>
          </td>
          <td>
            <p>臺南市北區林森路三段86巷2弄3號</p>
            <p>0926-057-609</p>
          </td>
          <td>
            <a target="_" href="http://msju2004.pixnet.net/blog">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>府城教師合唱團</p>
          </td>
          <td>
            <p>李瑪寶</p>
          </td>
          <td>
            <p>臺南市東區泉南里府連路326巷6號</p>
            <p>0936-258-020</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>大地合唱團</p>
          </td>
          <td>
            <p>莊信煌</p>
          </td>
          <td>
            <p>臺南市南區新義南路24號2樓</p>
            <p>06-261-4879</p>
          </td>
          <td>
            <a target="_" href="http://www.earthart.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台南市愛樂合唱團</p>
          </td>
          <td>
            <p>黃南海</p>
          </td>
          <td>
            <p>臺南市中西區健康路一段390巷26號</p>
            <p>0932-866-671</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>MP Singers混聲合唱團</p>
          </td>
          <td>
            <p>李瑪寶</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.facebook.com/MP-Singers-173637153206556/posts">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>希望種籽青少年兒童合唱團</p>
          </td>
          <td>
            <p>劉益廷</p>
          </td>
          <td>
            <p>臺南市北區賢北街25巷42號1樓</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>高雄室內合唱團</p>
          </td>
          <td>
            <p>翁佳芬</p>
          </td>
          <td>
            <p>高雄市苓雅區憲政路235號</p>
            <p>07-222-2358</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/高雄室內合唱團-Kaohsiung-Chamber-Choir-161258233928570/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄市佳音合唱團</p>
          </td>
          <td>
            <p>藍秀英</p>
          </td>
          <td>
            <p>高雄市前鎮區一心一路112號</p>
            <p>07-725-5007</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/高雄市佳音合唱團-102079534586981/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>世紀合唱團</p>
          </td>
          <td>
            <p>李仁傑</p>
          </td>
          <td>
            <p>高雄市新興區五福二路45之1號7樓</p>
            <p>07-215-7604</p>
          </td>
          <td>
            <a href="mailto:cycchoir@gmail.com">連結</a>
            <p></p>
          </td>
        </tr>
        <tr>
          <td>
            <p>城市擊樂團</p>
          </td>
          <td>
            <p>曾意鈞</p>
          </td>
          <td>
            <p>高雄市新興區八德一路186號</p>
            <p>07-236-5910</p>
          </td>
          <td>
            <a href="mailto:CTPE.KH@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>南台灣室內樂協會團</p>
          </td>
          <td>
            <p>吳亞欣</p>
          </td>
          <td>
            <p>高雄市苓雅區和平一路145巷21號5樓</p>
            <p>07-711-2618</p>
          </td>
          <td>
            <a target="_" href="https://www.stcms.org/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>天生歌手合唱團</p>
          </td>
          <td>
            <p>程偉嘉</p>
          </td>
          <td>
            <p>高雄市鼓山區大順一路638號15樓</p>
            <p>0937-025-252</p>
          </td>
          <td>
            <a href="mailto:natus.cantorum@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄市兒童合唱團</p>
          </td>
          <td>
            <p>劉慧兒</p>
          </td>
          <td>
            <p>高雄市鹽埕區五福四路183號</p>
            <p>07-521-0626</p>
          </td>
          <td>
            <a href="mailto:music4700@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄市漢聲合唱團</p>
          </td>
          <td>
            <p>李秋福</p>
          </td>
          <td>
            <p>高雄市苓雅區建國一路109號8樓</p>
            <p>0937-331-407</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HS.chorus">連結</a><br>
            <a href="mailto:cfleekhh@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>高雄愛樂室內合唱團</p>
          </td>
          <td>
            <p>周欣潔</p>
          </td>
          <td>
            <p>高雄市左營區南屏路376號7樓之2</p>
            <p>0986-099-633</p>
          </td>
          <td>
            <a href="mailto:kaohsiungpcc@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>屏東室內合唱團</p>
          </td>
          <td>
            <p>鍾佳諭</p>
          </td>
          <td>
            <p>屏東縣屏東市崇蘭里廣東路1496號</p>
            <p>08-756-0198</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pcc999/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>The Pure人聲樂團</p>
          </td>
          <td>
            <p>黃錦蘭</p>
          </td>
          <td>
            <p>屏東縣屏東市興豐路137巷7號1樓</p>
            <p>08-736-9441</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/ThePureBand/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>SURE人聲樂團</p>
          </td>
          <td>
            <p>甘聖竹</p>
          </td>
          <td>
            <p>屏東縣屏東市清溪里建國路217巷1之1號</p>
            <p>0920-284-449</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/singers.SURE/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Acapassion人聲樂團</p>
          </td>
          <td>
            <p>張淑娟</p>
          </td>
          <td>
            <p>屏東縣屏東市華山里華二街18號</p>
            <p>08-736-0330</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Acapassion阿卡佩炫人聲樂團-1029498567118113/about/?ref=page_internal">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>潮聲合唱團</p>
          </td>
          <td>
            <p>徐炳文</p>
          </td>
          <td>
            <p>屏東縣潮州鎮長興路54之10號</p>
            <p>08-788-3360</p>
          </td>
          <td>
            <a href="mailto:chen7883360@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Puzangalan兒童合唱團</p>
          </td>
          <td>
            <p>蔡義方</p>
          </td>
          <td>
            <p>屏東縣三地門鄉三地村中正路二段29巷2-2號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/PuzangalanChoir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>Sonar聲納合唱團</p>
          </td>
          <td>
            <p>戴世侃</p>
          </td>
          <td>
            <p>宜蘭縣羅東鎮北成路一段125號</p>
            <p>0952-334-388</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/sonar1998/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>蘭馨合唱團</p>
          </td>
          <td>
            <p>徐菊紅</p>
          </td>
          <td>
            <p>宜蘭縣宜蘭市復興里復興路一段121巷21弄13號</p>
          </td>
          <td>
            <a href="mailto:shu_3450@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>蘭陽兒童合唱團</p>
          </td>
          <td>
            <p>林小姐</p>
          </td>
          <td>
            <p>宜蘭縣宜蘭市中山路二段482號</p>
            <p>03-936-9115 #116</p>
          </td>
          <td>
            <a href="mailto:yilanperform@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>噶瑪蘭童聲合唱團</p>
          </td>
          <td>
            <p>王曉漢</p>
            <p>林采藜</p>
          </td>
          <td>
            <p>宜蘭縣宜蘭市泰山路85巷10號</p>
            <p>0933-770-734</p>
          </td>
          <td>
            <a href="mailto:tsaililin@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>花蓮合唱團</p>
          </td>
          <td>
            <p>吳明益</p>
          </td>
          <td>
            <p>花蓮縣花蓮市中美十街68巷2號</p>
            <p>0937-168-385</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HualienChoir/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>知音合唱團</p>
          </td>
          <td>
            <p>趙佩憶</p>
          </td>
          <td>
            <p>花蓮縣新城鄉北埔村民有街397號</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>台東室內合唱團</p>
          </td>
          <td>
            <p>張惠雯</p>
          </td>
          <td>
            <p>臺東縣臺東市中華路一段 519 號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TTNDChorus/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>拉縴人少年兒童合唱團</p>
          </td>
          <td>
            <p>廖偉瞱</p>
          </td>
          <td>
            <p>澎湖縣馬公市明遠路12巷7號</p>
            <p>0922-911-389</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>澎湖室內合唱團</p>
          </td>
          <td>
            <p>歐玉甄</p>
          </td>
          <td>
            <p>澎湖縣馬公市水源路2之1號7樓之2</p>
            <p>0963-193-696</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>菊之音室內合唱團</p>
          </td>
          <td>
            <p>柯仲甫</p>
          </td>
          <td>
            <p>澎湖縣馬公市光復路185之3號</p>
            <p>0933-373-286</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>菊之音兒童合唱團</p>
          </td>
          <td>
            <p>柯仲甫</p>
          </td>
          <td>
            <p>澎湖縣馬公市光復路185之3號</p>
            <p>0933-373-288</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>菊之音青少年合唱團</p>
          </td>
          <td>
            <p>柯仲甫</p>
          </td>
          <td>
            <p>澎湖縣馬公市光復路185之3號</p>
            <p>0933-373-290</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>星聲代合唱團</p>
          </td>
          <td>
            <p>廖偉曄</p>
          </td>
          <td>
            <p>澎湖縣馬公市明遠路12巷7號</p>
            <p>06-927-2779</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>金門縣合唱團</p>
          </td>
          <td>
            <p>黃小姐</p>
          </td>
          <td>
            <p>金門縣金城鎮環島北路一段66號（金門縣文化局2樓視聽教室）</p>
            <p>0953-014-721</p>
          </td>
          <td>
            <a href="mailto:kinmen6526371@yahoo.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>馬祖少年合唱團</p>
          </td>
          <td>
            <p>吳健忠</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://reurl.cc/OVGkv">連結</a>
          </td>
        </tr>
      </tbody>
    </table>
    <br />
    <h3>三、組織</h3>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>亞洲作曲家聯盟台灣總會</p>
          </td>
          <td>
            <p>呂文慈</p>
          </td>
          <td>
            <p>臺北市大安區信義路四段6號17樓之1</p>
            <p>02-2897-5900</p>
          </td>
          <td>
            <a target="_" href="http://www.acl-taiwan.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>中華民國現代音樂協會</p>
          </td>
          <td>
            <p>潘家琳</p>
          </td>
          <td>
            <p>02-2624-1091</p>
          </td>
          <td>
            <a target="_" href="http://iscmtw.blogspot.com/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>中華民國電腦音樂學會</p>
          </td>
          <td>
            <p>董昭民</p>
          </td>
          <td>
            <p>臺北市大安區德安里四維路52巷27之2號3樓</p>
          </td>
          <td>
            <a target="_" href="https://www.taiwancomputermusic.org/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北愛樂文教基金會</p>
          </td>
          <td>
            <p>劉葳莉</p>
          </td>
          <td>
            <p>臺北市大安區敦化南路一段233巷28號地下1樓</p>
            <p>02-2773-3691</p>
          </td>
          <td>
            <a target="_" href="http://www.tpf.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣室內樂藝術推廣協會</p>
          </td>
          <td>
            <p>廖皎含</p>
          </td>
          <td>
            <p>臺北市大安區杭州南路二段29-5號</p>
            <p>02-3322-1428</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/apstring">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>財團法人樂賞音樂教育基金會</p>
          </td>
          <td>
            <p>劉岠渭</p>
          </td>
          <td>
            <p>臺北市中山區民權東路一段55號7樓</p>
          </td>
          <td>
            <a target="_" href="http://www.poco-a-poco.org/pocoapoco/portal/PortalHome.asp">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>
              中華民國聲樂家協會
            </p>
          </td>
          <td>
            <p>孫清吉</p>
          </td>
          <td>
            <p>臺北市中正區忠孝東路二段29號2樓及3樓　</p>
            <p>02-3393-8779</p>
          </td>
          <td>
            <a target="_" href="http://www.vocalistasso.org.tw/front/bin/home.phtml">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>財團法人擊樂文教基金會</p>
          </td>
          <td>
            <p>朱宗慶</p>
          </td>
          <td>
            <p>臺北市北投區大業路10號6樓</p>
            <p>02-2891-9900</p>
          </td>
          <td>
            <a target="_" href="http://www.jpg.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>捌號會所</p>
          </td>
          <td>
            <p>林芳宜</p>
          </td>
          <td>
            <p>臺北市士林區雙溪街102號9樓</p>
          </td>
          <td>
            <a href="mailto:adm@studioacht.com.tw">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台北市新合唱文化藝術基金會</p>
          </td>
          <td>
            <p>洪光浩</p>
          </td>
          <td>
            <p>新北市中和區中和路266號8樓之3</p>
          </td>
          <td>
            <a target="_" href="http://www.tcmc.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>拉縴人文化基金會</p>
          </td>
          <td>
            <p>李曜州</p>
          </td>
          <td>
            <p>新北市新店區北新路三段205之3號7樓B室</p>
            <p>02-8913-2068</p>
          </td>
          <td>
            <a target="_" href="http://www.tmccaf.org.tw/">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>財團法人高雄市愛樂文化藝術基金會</p>
          </td>
          <td>
            <p>朱宏昌</p>
          </td>
          <td>
            <p>高雄市鳳山區光遠路161號</p>
            <p>07-743-6633</p>
          </td>
          <td>
            <a target="_" href="http://kpcaf.khcc.gov.tw/index.php?task=home&amp;lang=cht">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>臺灣擊樂藝術聯盟</p>
          </td>
          <td>
            <p>陳文姬</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.taiwanpercussionaa.com/">連結</a><br>
            <a href="mailto:tpaausa888@gmail.com">連結</a>
          </td>
        </tr>
        <tr>
          <td>
            <p>台灣管風琴協會</p>
          </td>
          <td>
            <p>劉信宏</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <a target="_" href="https://www.agotw.org/">連結</a><br>
            <a href="mailto:taiwanorgan@gmail.com">連結</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
