<template>
  <div>
    <div class="title">
      <h2>道、法教音樂篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width: 25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>臺北慈雲堂</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>臺北市內湖區康寧路一段156巷57號</p>
            <p>02-2790-8867</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pages/內湖慈雲堂/439338836649756/">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>北投代天府</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>臺北市豐年路一段35之1號</p>
            <p>02-2891-2767</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>創建於1974年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>松山慈惠堂</p>
          </td>
          <td>
            <p>郭葉子</p>
          </td>
          <td>
            <p>臺北市信義區福德街251巷33號</p>
            <p>02-2726-1735</p>
          </td>
          <td>
            <a target="_" href="https://www.sstht.org.tw/">連結</a>
          </td>
          <td>
            <p>成立於1969年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>南港天元殿</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>臺北市南港區三重路49號</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>三芝富福頂山寺</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市三芝區圓山里二坪頂69號</p>
            <p>02-2636-7002</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>三重天巡府</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市三重區五華街75巷4號2樓</p>
            <p>0910-346-099</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TianXunFu/">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>中和濟南宮</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市中和區福美路256巷10號</p>
            <p>02-2240-1253</p>
          </td>
          <td>
            <a target="_" href="https://m.facebook.com/profile.php?id=498374277037829">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>中國道教經典研究會</p>
          </td>
          <td>
            <p>道長</p>
            <p>陳炳松</p>
            <p>邱玉珠</p>
          </td>
          <td>
            <p>新北市石碇區豐田里磨石坑31號</p>
            <p>02-2663-9063</p>
            <p>0970-067-777</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>汐止拱北殿</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市汐止區汐萬路三段88號</p>
            <p>02-2646-1878</p>
          </td>
          <td>
            <a target="_" href="https://www.gbt.tw/h/Index?key=013215999296">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>金鳳山臺北慈靈宮</p>
          </td>
          <td>
            <p>邱師姐</p>
          </td>
          <td>
            <p>新北市石碇區豐田里磨石坑31號</p>
            <p>02-2663-9063</p>
            <p>0932-033-983</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>金瓜石五府宮</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市瑞芳區山尖路133號</p>
            <p>02-2496-2281</p>
          </td>
          <td>
            <a target="_" href="https://b-m.facebook.com/profile.php?id=427967313880463&amp;__tn__=%2As-R">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>淡水行天武聖宮</p>
          </td>
          <td>
            <p>主持</p>
            <p>陳俊廷</p>
          </td>
          <td>
            <p>新北市淡水區八勢路一段120號</p>
            <p>02-2809-2359</p>
          </td>
          <td>
            <a target="_" href="https://place-of-worship-1260.business.site/?utm_source=gmb&amp;utm_medium=referral">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>新北三清宮</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市板橋區文化路二段548巷8弄12號</p>
            <p>0929-544-999</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>萬里武聖堂</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市萬里區孝七街6號</p>
            <p>02-2492-1248</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/萬里協聖堂-1012797448753259/?rf=178375678899827">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>艋舺帝謙會</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市板橋區江寧路三段85巷5號</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/帝謙會-1396811787312015/">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>輔大宗教學系道教學術發展中心</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>新北市新莊區中正路510號</p>
            <p>02-2905-2791</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/DRS.FJCU/">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>正一道教廣盛壇</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>桃園大園區竹圍里竹圍街44-5號</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>中國武當道教太玄法師協會</p>
          </td>
          <td>
            <p>創會長</p>
            <p>蕭道賢</p>
          </td>
          <td>
            <p>臺中市北屯區和祥六街2號</p>
            <p>04-2436-4367</p>
            <p>0933-531-826</p>
          </td>
          <td>
            <a target="_" href="https://m.facebook.com/profile.php?id=269680476383444">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>臺中指微道壇</p>
          </td>
          <td>
            <p>道長</p>
            <p>林元啟</p>
          </td>
          <td>
            <p>臺中市烏日區中山路三段142號</p>
            <p>04-2338-1230</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pages/指微道壇/319828351391229">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>竹山守真道房</p>
          </td>
          <td>
            <p>道長</p>
            <p>陳光村</p>
          </td>
          <td>
            <p>南投縣竹山鎮中山里鯉南路1號（陳東成擇日館）</p>
            <p>04-9264-3871</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/stoneace/">連結</a>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>海頭社文龍殿</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>臺南市安平區安北路121巷10弄6號</p>
            <p>06-2286-931</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>創建於1817年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>礁溪明德道院（前身：三重玉勅明德壇）</p>
          </td>
          <td>
            <p>道長</p>
            <p>蘇西明</p>
          </td>
          <td>
            <p>宜蘭縣礁溪鄉吳沙村四結33-10號</p>
            <p>02-2978-2428</p>
            <p>0936-050-367</p>
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/groups/taiwan.mingde/">連結</a>
          </td>
          <td>
            <p>弘道會成立於2012年</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>蘇澳指南宮</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>宜蘭縣蘇澳鎮冷泉路9之1號</p>
            <p>03-997-2213</p>
          </td>
          <td>&nbsp;</td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>塘岐蕭王府廟</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>連江縣北竿鄉中正路70號</p>
            <p>08-3656-559</p>
          </td>
          <td>
              <a target="_" href="https://memory.culture.tw/Home/Detail?Id=154716&amp;IndexCode=Culture_Place">連結</a>
          </td>
          <td>
            <p>創建於1977年</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
